services:
  kreston-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kreston-apps
    restart: unless-stopped
    network_mode: host
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false