name: CI/CD Deploy to Local Server

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Files & Run Docker Compose
        run: |
          # Menyalin seluruh file hasil checkout GitHub ke folder proyek utama di server
          # Sesuaikan nama folder _work jika berbeda, biasanya mengikuti nama repository
          cp -r . /docker/kreston-apps/
          
          # Masuk ke folder utama aplikasi di server
          cd /docker/kreston-apps
          
          # Jalankan Docker Compose
          docker compose down
          docker compose up -d --build
          docker exec kreston-apps php artisan config:clear
          docker exec kreston-apps php artisan cache:clear
          docker exec kreston-apps php artisan migrate --force